spring:
  application:
    name: manager-doctor-appointment

  datasource:
    url: jdbc:postgresql://localhost:5432/doctor-appointment
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.demo.manager.doctorappointment.util.serialization.kafka.CustomSerializer
    topic:
      name:
        appointment_history

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9001