apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-service
  name: postgresql-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: postgresql-pv-claim
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql-deployment
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
      name: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: postgresql-persistent
      volumes:
        - name: postgresql-persistent
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
  replicas: 1
